
// launchAnimations.js
const launchAnimations = (board, type, object) => {
  // 1. Grab the static array of nodes generated by your algorithm
  const nodes = object ? [...board.objectNodesToAnimate] : [...board.nodesToAnimate];
  
  // 2. Determine speed
  const speed = board.speed === "fast" ? 10 : board.speed === "average" ? 50 : 150;

  // 3. Clear board state safely before starting
  if (object) {
      board.objectNodesToAnimate = [];
  } else {
      board.nodesToAnimate = [];
  }

  // 4. Use a standard for-loop to queue animations efficiently
  for (let i = 0; i <= nodes.length; i++) {
    // If we reached the end of the search, animate the shortest path
    if (i === nodes.length) {
      setTimeout(() => {
        animateShortestPath(board, type, object);
      }, speed * i);
      return; 
    }

    // Otherwise, animate the searching process
    setTimeout(() => {
      const currentNode = nodes[i];
      const htmlNode = document.getElementById(currentNode.id);
      
      // Skip if it's a special node (start, target, object)
      const specialClasses = ["start", "target", "object", "visitedStartNodeBlue", "visitedTargetNodeBlue"];
      const isSpecial = specialClasses.some(c => htmlNode.classList.contains(c));

      if (!isSpecial) {
         htmlNode.classList.add("visited");
         if (currentNode.weight === 15) {
             htmlNode.classList.add("weight");
         }
      }
    }, speed * i); // <-- The magic: multiplies delay by index
  }
};

// Separating out the shortest path logic keeps the main loop clean
const animateShortestPath = (board, type, object) => {
  const shortestNodes = object ? 
      [...board.objectShortestPathNodesToAnimate, ...board.shortestPathNodesToAnimate] : 
      [...board.shortestPathNodesToAnimate];

  for (let i = 0; i < shortestNodes.length; i++) {
    setTimeout(() => {
      const currentNode = shortestNodes[i];
      const htmlNode = document.getElementById(currentNode.id);
      
      htmlNode.classList.remove("visited"); // Clean up previous classes
      htmlNode.classList.add("shortest-path");

      // Add directional classes if needed for your CSS
      if (type !== "unweighted" && currentNode.direction) {
          htmlNode.classList.add(`shortest-path-${currentNode.direction}`);
      }
    }, 40 * i);
  }
  
  // Re-enable UI buttons once animation finishes
  setTimeout(() => {
      board.toggleButtons();
  }, 40 * shortestNodes.length);
};

module.exports = launchAnimations;





    
