// launchAnimations.js

// Tracks the current animation "run" so that a new call to
// launchAnimations can invalidate any still-pending setTimeout
// callbacks from a previous run (e.g. if the user clicks "Visualize"
// again, or resets the board, before the last animation finished).
let currentRunId = 0;

const WEIGHTED_NODE_VALUE = 15; // matches the weight assigned to a "weight" node elsewhere in the algorithms

const launchAnimations = (board, type, object) => {
  const runId = ++currentRunId;

  // 1. Grab the static array of nodes generated by your algorithm
  const nodes = object ? [...board.objectNodesToAnimate] : [...board.nodesToAnimate];

  // 2. Determine speed
  const speed = board.speed === "fast" ? 10 : board.speed === "average" ? 50 : 150;

  // 3. Clear board state safely before starting
  if (object) {
    board.objectNodesToAnimate = [];
  } else {
    board.nodesToAnimate = [];
  }

  // 4. Use a standard for-loop to queue animations efficiently
  for (let i = 0; i <= nodes.length; i++) {
    // If we reached the end of the search, animate the shortest path
    if (i === nodes.length) {
      setTimeout(() => {
        if (runId !== currentRunId) return; // a newer run started — abandon this one
        animateShortestPath(board, type, object, runId);
      }, speed * i);
      return;
    }

    // Otherwise, animate the searching process
    setTimeout(() => {
      if (runId !== currentRunId) return; // a newer run started — abandon this one

      const currentNode = nodes[i];
      const htmlNode = document.getElementById(currentNode.id);
      if (!htmlNode) return; // node no longer in the DOM (board was reset/regenerated)

      // Skip if it's a special node (start, target, object)
      const specialClasses = ["start", "target", "object", "visitedStartNodeBlue", "visitedTargetNodeBlue"];
      const isSpecial = specialClasses.some(c => htmlNode.classList.contains(c));
      if (!isSpecial) {
        htmlNode.classList.add("visited");
        if (currentNode.weight === WEIGHTED_NODE_VALUE) {
          htmlNode.classList.add("weight");
        }
      }
    }, speed * i); // <-- The magic: multiplies delay by index
  }
};

// Separating out the shortest path logic keeps the main loop clean
const animateShortestPath = (board, type, object, runId) => {
  const shortestNodes = object ?
    [...board.objectShortestPathNodesToAnimate, ...board.shortestPathNodesToAnimate] :
    [...board.shortestPathNodesToAnimate];

  for (let i = 0; i < shortestNodes.length; i++) {
    setTimeout(() => {
      if (runId !== currentRunId) return; // a newer run started — abandon this one

      const currentNode = shortestNodes[i];
      const htmlNode = document.getElementById(currentNode.id);
      if (!htmlNode) return; // node no longer in the DOM

      htmlNode.classList.remove("visited"); // Clean up previous classes
      htmlNode.classList.add("shortest-path");
      // Add directional classes if needed for your CSS
      if (type !== "unweighted" && currentNode.direction) {
        htmlNode.classList.add(`shortest-path-${currentNode.direction}`);
      }
    }, 40 * i);
  }

  // Re-enable UI buttons once animation finishes
  setTimeout(() => {
    if (runId !== currentRunId) return; // a newer run started — don't re-enable on its behalf
    board.toggleButtons();
  }, 40 * shortestNodes.length);
};

module.exports = launchAnimations;








    
